Add french translations
lainsce/yishu pull request #30
Opened 2019-01-17 20:58 UTC by NathanBnm

2019-01-18 11:40 UTC, lainsce commented
Please, use a file `fr.po` instead of using the Catalan translation file. Thanks.

2019-01-18 11:40 UTC, lainsce requested changes
Use fr.po

2019-01-18 15:04 UTC, NathanBnm commented
I had to fork again to reset changes concerning ca.po, so I opened #31

2019-01-19 14:46 UTC, lainsce commented
Gonna close this then.

2019-01-19 14:46 UTC, closed without merging